-- apply changes
create table audit_log (
  id                            bigint generated by default as identity not null,
  tenant_id                     bigint not null,
  created_at                    timestamptz not null,
  deleted                       boolean default false not null,
  version                       integer not null,
  when_created                  timestamptz not null,
  when_modified                 timestamptz not null,
  entity_name                   varchar(255) not null,
  unique_identifier             varchar(255) not null,
  action                        varchar(8) not null,
  user_id                       varchar(255) not null,
  client_ip                     varchar(255) not null,
  old_data                      jsonb,
  new_data                      jsonb,
  notes                         varchar(255),
  who_created                   varchar(255) not null,
  who_modified                  varchar(255) not null,
  constraint ck_audit_log_action check ( action in ('CREATE','UPDATE','PATCH','DELETE','MIGRATE','RE_INDEX')),
  constraint pk_audit_log primary key (id)
);

create table data_model (
  id                            bigint generated by default as identity not null,
  tenant_id                     bigint not null,
  schema_id                     bigint not null,
  deleted                       boolean default false not null,
  version                       integer not null,
  when_created                  timestamptz not null,
  when_modified                 timestamptz not null,
  data                          jsonb not null,
  unique_identifier             varchar(255) not null,
  entity_name                   varchar(255) not null,
  version_name                  varchar(255) not null,
  who_created                   varchar(255) not null,
  who_modified                  varchar(255) not null,
  constraint uq_data_model_unique_identifier_entity_name_version_name__1 unique (unique_identifier,entity_name,version_name,tenant_id),
  constraint pk_data_model primary key (id)
);

create table data_search_model (
  id                            bigint generated by default as identity not null,
  tenant_id                     bigint not null,
  array_idx                     integer,
  data_created_at               timestamptz,
  data_modified_at              timestamptz,
  deleted                       boolean default false not null,
  version                       integer not null,
  when_created                  timestamptz not null,
  when_modified                 timestamptz not null,
  entity_name                   varchar(255) not null,
  unique_identifier             varchar(255) not null,
  json_path                     varchar(255) not null,
  value                         jsonb not null,
  value_type                    varchar(7) not null,
  who_created                   varchar(255) not null,
  who_modified                  varchar(255) not null,
  constraint ck_data_search_model_value_type check ( value_type in ('STRING','NUMBER','BOOLEAN','OBJECT','ARRAY','NULL')),
  constraint pk_data_search_model primary key (id)
);

create table report_execution_log (
  id                            bigint generated by default as identity not null,
  tenant_id                     bigint not null,
  report_id                     bigint not null,
  started_at                    timestamptz,
  completed_at                  timestamptz,
  execution_time_ms             bigint,
  error_message                 TEXT,
  row_count                     integer,
  file_size_bytes               bigint,
  deleted                       boolean default false not null,
  version                       integer not null,
  when_created                  timestamptz not null,
  when_modified                 timestamptz not null,
  job_id                        varchar(255),
  status                        varchar(9) not null,
  execution_type                varchar(11),
  local_file_path               varchar(255),
  s3_bucket_name                varchar(255),
  s3_object_key                 varchar(255),
  file_format                   varchar(4) not null,
  storage_location              varchar(5) not null,
  execution_metadata            json not null,
  requested_by                  varchar(255),
  scheduler_job_id              varchar(255),
  who_created                   varchar(255) not null,
  who_modified                  varchar(255) not null,
  constraint ck_report_execution_log_status check ( status in ('PENDING','RUNNING','COMPLETED','FAILED','CANCELLED')),
  constraint ck_report_execution_log_execution_type check ( execution_type in ('MANUAL','SCHEDULED','API_REQUEST')),
  constraint ck_report_execution_log_file_format check ( file_format in ('CSV','JSON','XLS','XLSX')),
  constraint ck_report_execution_log_storage_location check ( storage_location in ('NONE','LOCAL','S3','BOTH')),
  constraint report_execution_job_id_idx unique (job_id),
  constraint pk_report_execution_log primary key (id)
);

create table report_model (
  id                            bigint generated by default as identity not null,
  tenant_id                     bigint not null,
  sql                           TEXT not null,
  is_active                     boolean default false not null,
  deleted                       boolean default false not null,
  version                       integer not null,
  when_created                  timestamptz not null,
  when_modified                 timestamptz not null,
  name                          varchar(255) not null,
  execution_type                varchar(9) not null,
  cron_schedule                 varchar(255),
  completion_actions            jsonb not null,
  file_format                   varchar(4) not null,
  who_created                   varchar(255) not null,
  who_modified                  varchar(255) not null,
  constraint ck_report_model_execution_type check ( execution_type in ('ADHOC','SCHEDULED','BOTH')),
  constraint ck_report_model_file_format check ( file_format in ('CSV','JSON','XLS','XLSX')),
  constraint report_name_idx unique (name,tenant_id),
  constraint pk_report_model primary key (id)
);

create table schema_model (
  id                            bigint generated by default as identity not null,
  tenant_id                     bigint not null,
  is_validation_enabled         boolean default false not null,
  deleted                       boolean default false not null,
  version                       integer not null,
  when_created                  timestamptz not null,
  when_modified                 timestamptz not null,
  entity_name                   varchar(255) not null,
  json_schema                   jsonb not null,
  version_name                  varchar(255) not null,
  unique_identifier_formatter   varchar(255) not null,
  indexed_json_paths            jsonb not null,
  lifecycle_scripts             jsonb not null,
  who_created                   varchar(255) not null,
  who_modified                  varchar(255) not null,
  constraint uq_schema_model_entity_name_version_name_tenant_id unique (entity_name,version_name,tenant_id),
  constraint pk_schema_model primary key (id)
);

create table tenant_model (
  id                            bigint generated by default as identity not null,
  is_active                     boolean default false not null,
  deleted                       boolean default false not null,
  version                       integer not null,
  when_created                  timestamptz not null,
  when_modified                 timestamptz not null,
  name                          varchar(255) not null,
  domain                        varchar(255) not null,
  description                   varchar(255),
  settings                      jsonb not null,
  config                        jsonb not null,
  allowed_ips                   jsonb,
  who_created                   varchar(255) not null,
  who_modified                  varchar(255) not null,
  constraint uq_tenant_model_domain unique (domain),
  constraint pk_tenant_model primary key (id)
);

-- foreign keys and indices
create index ix_data_model_schema_id on data_model (schema_id);
alter table data_model add constraint fk_data_model_schema_id foreign key (schema_id) references schema_model (id) on delete restrict on update restrict;

alter table report_execution_log add constraint fk_report_execution_log_report_id foreign key (report_id) references report_model (id) on delete restrict on update restrict;

create index if not exists ix_audit_log_tenant_id_entity_name_action_created_at_uniq_1 on audit_log (tenant_id,entity_name,action,created_at,unique_identifier,user_id);
create index if not exists ix_audit_log_tenant_id on audit_log (tenant_id);
CREATE INDEX search_gin_data ON data_model USING GIN(data jsonb_path_ops);
create index if not exists ix_data_model_tenant_id on data_model (tenant_id);
CREATE INDEX search_value_numeric ON data_search_model USING BTREE (((value->'value')::numeric)) where value_type = 'NUMBER';
CREATE INDEX search_value_text ON data_search_model USING BTREE ((value->>'value')) where value_type = 'STRING';
CREATE INDEX search_value_text ON data_search_model USING BTREE (((value->'value')::boolean)) where value_type = 'BOOLEAN';
CREATE INDEX search_value_gin ON data_search_model USING GIN((value->'value') jsonb_path_ops);
CREATE INDEX search_gin ON data_search_model USING GIN(value jsonb_path_ops);
create index if not exists ix_data_search_model_tenant_id on data_search_model (tenant_id);
create index if not exists ix_data_search_model_entity_name on data_search_model (entity_name);
create index if not exists report_execution_report_id_idx on report_execution_log (report_id);
create index if not exists report_execution_status_idx on report_execution_log (status,storage_location);
create index if not exists ix_report_execution_log_tenant_id on report_execution_log (tenant_id);
create index if not exists ix_report_model_tenant_id on report_model (tenant_id);
create index if not exists ix_schema_model_tenant_id on schema_model (tenant_id);
